import React from "react";
import Head from "next/head";

const success = () => {
  return (
    <>
      <Head>
        <title>Order Delivered</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center text-4xl text-gray-900 h-screen w-full font-bold">
        Your order has been successfully delivered.{" "}
        <span className="w-10 h-10 rounded-full bg-red-400 animate-pulse m-2"></span>
      </div>
    </>
  );
};

export default success;
